---
# Source: example-v2/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-example-v2
  labels:
    app.kubernetes.io/name: example-v2
    helm.sh/chart: example-v2-0.2.7
    app.kubernetes.io/instance: my-example-v2
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: example-v2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-example-v2
  labels:
    app.kubernetes.io/name: example-v2
    helm.sh/chart: example-v2-0.2.7
    app.kubernetes.io/instance: my-example-v2
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: example-v2
    app.kubernetes.io/instance: my-example-v2
---
# Source: example-v2/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-example-v2
  labels:
    app.kubernetes.io/name: example-v2
    helm.sh/chart: example-v2-0.2.7
    app.kubernetes.io/instance: my-example-v2
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example-v2
      app.kubernetes.io/instance: my-example-v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-v2
        app.kubernetes.io/instance: my-example-v2
    spec:
      serviceAccountName: my-example-v2
      securityContext:
        {}
      containers:
        - name: example-v2
          securityContext:
            {}
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: example-v2/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-example-v2
  labels:
    app.kubernetes.io/name: example-v2
    helm.sh/chart: example-v2-0.2.7
    app.kubernetes.io/instance: my-example-v2
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - "chart-example.local"
      secretName: chart-example-tls
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-example-v2
                port:
                  number: 80
---
# Source: example-v2/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "my-example-v2-test-connection"
  labels:
    app.kubernetes.io/name: example-v2
    helm.sh/chart: example-v2-0.2.7
    app.kubernetes.io/instance: my-example-v2
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['my-example-v2:80']
  restartPolicy: Never
